### ISSUE TITLE
Update messages for 1.10

### ISSUE THREAD

**Issue by grahamtriggs** [VIVO-DE/Vitro-languages#1]
Vitro changed keys

external_login_text
minimum_password_length
individual_not_found

---------------------

Vitro Added

minimum_ymd
page_not_created
display_more_ellipsis
faux_property_listing
decimal_only
save_entry
base_property_capitalized
invalid_format
for
minimum_hour
change_text_for
no_class_restrictions
add_an_entry_to
individual_not_found_msg
december
page_not_found_msg
page_uri_missing_msg
page_uri_missing
faux_property_capitalized
year_numeric
whole_number
dump_restore
faux_property_by_base
select_existing
four_digit_year
to
year_month_day
show_more_content
display_less
add_new_entry_for
change_entry_for
download_results
year_month
faux_property_alpha
page_not_created_msg
search_individual_results
select_class_for_search
range_data_type
page_not_found
select_a_language

**Comment by hauschke** [comment]
Done.

https://github.com/VIVO-DE/Vitro-languages/commit/2bbe87a18252ecf19e543b4435c972b6b64de930 #
